#!/bin/bash
#
# chkconfig: 35 90 12
#
# description: shadowsocks server

. /etc/init.d/functions

start() {
    ssserver -p 443 -k ht12345whthfk -m rc4-md5 --user nobody -d start
    ### Create the lock file ###
    touch /var/lock/subsys/ssservice
    success $"Shadowsocks server startup"
    echo
}

stop() {
    ssserver -d stop
    ### Now, delete the lock file ###
    rm -f /var/lock/subsys/ssservice
    echo
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status ssservice
        ;;
    restart|reload|condrestart)
        stop
        start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0

